services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: blablabook-client
    command:
      ["sh", "-c", "cp -r /usr/share/nginx/html/* /shared/ && sleep infinity"]
    volumes:
      - client_dist:/shared

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: blablabook-api
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=3000
      - REDIS_URL=${REDIS_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:1.29-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./servers/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./servers/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./servers/ssl:/etc/nginx/ssl:ro
      - client_dist:/usr/share/nginx/html:ro
    depends_on:
      - api
      - client

  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db_data:
  redis-data:
  client_dist:
